
version: '2'

services:
  web-server:
    build: .
    environment:
      - POSTGRES_URL="${DB_URL}"
    ports:
      - "8080:80"
    depends_on: ["postgres"]
    links: ["postgres"]

  postgres:
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER="${POSTGRES_USER}"
      - POSTGRES_PASSWORD="${DB_PASSWORD}"
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports: ["5433:5433"]
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.b/create_tables.sql

